export const DEPARTMENTS = [
  "Administrativo",
  "AGEHAB",
  "Assistência Técnica",
  "Cobrança",
  "Comercial",
  "Contabilidade",
  "Crédito",
  "Desenvolvimento Imobiliário",
  "Diretoria",
  "Engenharia",
  "Experiência do Cliente (CX)",
  "Financeiro",
  "Financiamento a Produção",
  "FP&A",
  "Gente e Cultura",
  "Gestão de Despesas",
  "Inovação e Tecnologia",
  "Jurídico",
  "Marketing",
  "Novos Negócios",
  "Obra",
  "Orçamento",
  "Orçamento, Planejamento e Controle",
  "Processos",
  "Qualidade",
  "Secretaria de Vendas",
  "SESMT",
  "Suprimentos",
  "TI",
] as const;

export type Department = (typeof DEPARTMENTS)[number];
